34 add additional characteristics to profile
UniversalDot/UniversalDot-node pull request #47
Opened 2022-06-11 09:23 UTC by vivekvpandya

2022-06-11 17:00 UTC, JosephKnecht-lab requested changes

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/profile/src/lib.rs
> +		pub name: BoundedVec<u8, T::MaxStringLen>,
You changed it because we want to limit the string length?

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/profile/src/lib.rs
> +				available_hours_per_week: 40,
Don't hardcode it to 40, but rather take it as an input to generate_profile()

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/profile/src/lib.rs
> +			Self::profiles(owner).ok_or(<Error<T>>::NoProfileCreated)?;
What happens when someone with a different profile tries to delete another profile?

2022-06-11 17:00 UTC, stojanov-igor commented on runtime/src/lib.rs
> +	pub const MaxStringLen: u32 = 256;
`MaxUsernameLen` would be a better name? How did you come up with 256? How many characters would that be?

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/task/src/tests.rs
> +		assert_ok!(Profile::create_profile(Origin::signed(1), USERNAME.to_vec().try_into().unwrap(), Vec::new().try_into().unwrap()));
`to_vec().try_into().unwrap()`.. shouldn't we try to create a BoundedVec instead? chaining 3 methods is too much..

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/profile/src/benchmarking.rs
> +	}: update_profile(RawOrigin::Signed(update_account_caller), username.try_into().unwrap(), interests.try_into().unwrap(), 40_u8)
Create a variable rather than adding `40-u8`

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/profile/src/lib.rs
> +		pub fn update_additional_information(origin: OriginFor<T>, additional_information :
We don't need a new extrinsic to change additional information. Additional information can be changed through update_profile.

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/profile/src/lib.rs
> +	pub(super) type AdditionalInformation<T: Config> = StorageMap<_, Twox64Concat, T::AccountId,
You don't need additional storage items. Additional Information should be added to the Profile Struct, just like available hours.

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/profile/src/tests.rs
> +		assert_noop!(Profile::update_profile(Origin::signed(2), USERNAME.to_vec().try_into().unwrap(), vec2.try_into().unwrap(), 20_u8), Error::<Test>::NoProfileCreated);
The previous error message was more descriptive. Revert to previous error

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/profile/src/tests.rs
> +		assert_ok!(Profile::update_additional_information(Origin::signed(1),
Additional information should be updated to update_profile.

2022-06-11 17:00 UTC, stojanov-igor commented on pallets/profile/src/tests.rs
> +		assert_eq!(profile.available_hours_per_week, 20_u8);
Good.

2022-06-12 05:12 UTC, vivekvpandya commented on pallets/profile/src/lib.rs
> +		pub name: BoundedVec<u8, T::MaxStringLen>,
usually we should use BoundedVec<> in substrate storage.

2022-06-12 05:14 UTC, vivekvpandya commented on pallets/profile/src/lib.rs
> +			Self::profiles(owner).ok_or(<Error<T>>::NoProfileCreated)?;
Is that possible? How can we make a signed extrinsic for some one else's account?

2022-06-12 05:16 UTC, vivekvpandya commented on pallets/profile/src/tests.rs
> +		assert_noop!(Profile::update_profile(Origin::signed(2), USERNAME.to_vec().try_into().unwrap(), vec2.try_into().unwrap(), 20_u8), Error::<Test>::NoProfileCreated);
AFAIU in current implementation there is not way to read/write other user's profile data.

2022-06-12 05:16 UTC, vivekvpandya commented on pallets/profile/src/tests.rs
> +		assert_ok!(Profile::update_additional_information(Origin::signed(1),
Okay, I thought it may be efficient to have separate storage for additional_information

2022-06-12 05:21 UTC, vivekvpandya commented on pallets/task/src/tests.rs
> +		assert_ok!(Profile::create_profile(Origin::signed(1), USERNAME.to_vec().try_into().unwrap(), Vec::new().try_into().unwrap()));
No much better options, I can use unchecked method but that does not sound good practice for BoundedVec

2022-06-12 18:08 UTC, JosephKnecht-lab commented on pallets/profile/src/tests.rs
> +		assert_noop!(Profile::update_profile(Origin::signed(2), USERNAME.to_vec().try_into().unwrap(), vec2.try_into().unwrap(), 20_u8), Error::<Test>::NoProfileCreated);
You are right. I think its better as you have it.

2022-06-12 18:08 UTC, JosephKnecht-lab commented on pallets/profile/src/tests.rs
> +		assert_noop!(Profile::update_profile(Origin::signed(2), USERNAME.to_vec().try_into().unwrap(), vec2.try_into().unwrap(), 20_u8), Error::<Test>::NoProfileCreated);
You are right. I think its better as you have it.

2022-06-12 18:10 UTC, JosephKnecht-lab commented on pallets/profile/src/lib.rs
> +			Self::profiles(owner).ok_or(<Error<T>>::NoProfileCreated)?;
You are right. we do ` ensure_signed(origin)?;` before we get into delete_profile.

2022-06-13 05:35 UTC, vivekvpandya commented on runtime/src/lib.rs
> +	pub const MaxStringLen: u32 = 256;
256 chars of u8. Nothing specific about this number.

2022-06-13 09:23 UTC, JosephKnecht-lab approved these changes

2022-06-13 09:24 UTC, merged